"""stage_d: add learner_goal, learner_task, mistake_record tables

Revision ID: 20260517_stage_d
Revises: 20260514_stage_c_course_content
Create Date: 2026-05-17

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260517_stage_d'
down_revision = '20260514_stage_c_course_content'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_goal',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('learner_id', sa.String(), nullable=False),
        sa.Column('course_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(), server_default='pending', nullable=False),
        sa.Column('progress', sa.Float(), server_default='0.0', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learner_goal_learner_id', 'learner_goal', ['learner_id'])
    
    op.create_table('learner_task',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('goal_id', sa.String(), nullable=True),
        sa.Column('learner_id', sa.String(), nullable=False),
        sa.Column('knowledge_point_id', sa.String(), nullable=True),
        sa.Column('exercise_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('type', sa.String(), server_default='learn', nullable=False),
        sa.Column('status', sa.String(), server_default='pending', nullable=False),
        sa.Column('priority', sa.Integer(), server_default='3', nullable=False),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learner_task_learner_id', 'learner_task', ['learner_id'])
    
    op.create_table('mistake_record',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('learner_id', sa.String(), nullable=False),
        sa.Column('exercise_id', sa.String(), nullable=False),
        sa.Column('knowledge_point_id', sa.String(), nullable=False),
        sa.Column('first_wrong_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('wrong_count', sa.Integer(), server_default='1', nullable=False),
        sa.Column('last_attempt_answer', sa.JSON(), nullable=True),
        sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mistake_record_learner_id', 'mistake_record', ['learner_id'])
    op.create_index('ix_mistake_record_exercise_id', 'mistake_record', ['exercise_id'])
    op.create_index('ix_mistake_record_kp_id', 'mistake_record', ['knowledge_point_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mistake_record_kp_id', table_name='mistake_record')
    op.drop_index('ix_mistake_record_exercise_id', table_name='mistake_record')
    op.drop_index('ix_mistake_record_learner_id', table_name='mistake_record')
    op.drop_table('mistake_record')
    
    op.drop_index('ix_learner_task_learner_id', table_name='learner_task')
    op.drop_table('learner_task')
    
    op.drop_index('ix_learner_goal_learner_id', table_name='learner_goal')
    op.drop_table('learner_goal')
    # ### end Alembic commands ###
